

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: piercap
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    volumes: 
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: supersecret
    ports:
      - "5050:80" 
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - postgres

networks: 
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: